name: cmu-ml
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - jupyterlab
  - notebook
  - ipykernel
  - pip
  - pip:
      - torch
      - torchvision
      - torchaudio
      - tensorflow
